logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE

spring:
  security:
    csrf:
      enabled: false

  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    #        generate_statistics: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://aruthabackend.postgres.database.azure.com:5432/postgres?&sslmode=require
    username: adminArutha
    password: coolpixl320C
    driver-class-name: org.postgresql.Driver
  server:
    servlet:
      context-path: /api
      error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_trace_param
        include-exception: true
