# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ vars.BACKEND_URL }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "/home/runner/Arutha-Backend/Arutha-Backend/*"
          target: "~/source"
      - name: Delete artifact from build
        uses: geekyeggo/delete-artifact@v2
        with:
          name: java-app
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mv ~/source/github/workspace/fc-connect-0.0.1-SNAPSHOT-latest.jar ~/source/github/workspace/fc-connect-0.0.1-SNAPSHOT-old.jar
            mv ~/source/github/workspace/fc-connect-0.0.1-SNAPSHOT.jar ~/source/github/workspace/fc-connect-0.0.1-SNAPSHOT-latest.jar
            rm ~/source/github/workspace/fc-connect-0.0.1-SNAPSHOT-old.jar
            sudo /etc/init.d/fc-connect-backend restart
